---
title: "PSTAT 127 HMWK 2"
author: "Kevin Ayala"
date: "1/31/2019"
output: pdf_document
---


```{r}
library(faraway)
library(tidyverse)
#Question 1
#a 
binreg <- glm(Class~., data = wbca, family = "binomial")
summary(binreg)
 # residual deviance is 89.464  on 671  degrees of freedom
```

For part B, $$\phi = \frac{residual deviance}{df}$$

```{r}
#b 
#from part a summary, residuals = 89.464 and degrees of freedom = 671
#pearson chisquare statistics residual is 
estimate <- 89.464/671
estimate
#our estimate is .1333294, which is rather poor compared to 1, thus model may need to be refined
#does not seem a plausable model


#c
AICselection <- step(binreg, direction = "backward")
AICselection
# best model has a min AIC score of 105.66
#with predictors thick, BNucl, Chrom, Adhes, NNuc1,Mitos, UShap

#d
x<-matrix(data=NA, nrow = 1,ncol = 7)
x[]<-c(4,1,3,1,1,1,1)
x <- as.data.frame(x)
names(x)<- c("Thick", "BNucl", "Chrom", "Adhes", "NNucl", "Mitos", "UShap")

reducedmodel <- glm(Class ~ Thick + BNucl + Chrom + Adhes + NNucl + Mitos + UShap, data = wbca, family  = "binomial")
summary(reducedmodel)
tumorAprob<-predict.glm(object = reducedmodel, newdata = x, type = "response")
tumorAlogodds <-predict.glm(object = reducedmodel, newdata = x, type = "link")

InfoA <- matrix(ncol = 2, nrow = 1, data = NA)
InfoA[1] <- tumorAprob
InfoA[2] <- tumorAlogodds
InfoA = as.data.frame(InfoA)
names(InfoA) = c("Probability","Log Odds")
InfoA 
#info regarding probability and log odds for Tumor A being benign

#e
y<-matrix(data=NA, nrow = 1,ncol = 7)
y[]<-c(3,1,3,1,1,1,1)
y <- as.data.frame(y)
names(y)<- c("Thick", "BNucl", "Chrom", "Adhes", "NNucl", "Mitos", "UShap")
y

tumorBprob<-predict.glm(object = reducedmodel, newdata = y, type ="response")
tumorBlogodds <- predict.glm(object = reducedmodel, newdata = y, type ="link")
InfoB <- matrix(ncol = 2, nrow = 1, data = NA)
InfoB[1] <- tumorBprob
InfoB[2] <- tumorBlogodds
InfoB = as.data.frame(InfoB)
names(InfoB) = c("Probability","Log Odds")
InfoB 
InfoB-InfoA #differences
#tumor B is higher in log odds than tumor A by .6216 

-.81489 - (.8529*1.96)
```

```{r}
#f
tumorA_errors<-predict.glm(object = reducedmodel, newdata = wbca, type = "response")
errors_tumorA <- ifelse(tumorA_errors < .5, 0 ,1)
tumorA_mislassified<-length(which(errors_tumorA != wbca$Class))
tumorA_mislassified #20 total subjects have been misclassified under the reduced model for tumor A

test<-cbind(True=wbca$Class, Predicted=errors_tumorA)
test <- as.data.frame(test)
errors<-filter(test, test$True != test$Predicted)
filter(errors, True == "1")
# 9 cases of tumors that are benign have been misclassified
#20-9 = 11, thus 11 cases of malignant have been misclassified

```